# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Singleton
version:      0.07
version_from: lib/Apache/Singleton.pm
installdirs:  site
requires:
    mod_perl:                      0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
