---
abstract: 'Singleton class for mod_perl'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Apache2::RequestIO: 0
  Apache2::RequestRec: 0
  Apache::Test: 0
  Apache::TestRequest: 0
  Apache::TestRunPerl: 0
  Mock::Apache: 0
  Module::Signature: 0
  Socket: 0
  Test::More: 0
  mod_perl: 0
  mod_perl2: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-Singleton
requires:
  Apache: 0
  Apache2::RequestUtil: 0
  Apache::Test: 1.35
  CGI: 3.12
  constant: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Apache-Singleton
  homepage: http://search.cpan.org/dist/Apache-Singleton/
  repository: git://github.com/mschout/apache-singleton.git
version: 0.12
